dist: bionic
language: ruby
rvm: 2.7
before_install:
  - export TENSORFLOW_VERSION=2.3.0
  - ./test/ci/install_tensorflow.sh
  - export LD_LIBRARY_PATH=$HOME/tensorflow/$TENSORFLOW_VERSION/lib:$LD_LIBRARY_PATH
cache:
  bundler: true
  directories:
    - $HOME/tensorflow
    - $HOME/.keras
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
